### ISSUE TITLE
Error when combining delete_versions and h5repack on empty Dataset

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#244] opened 2023-02-18 14:41 UTC
We are encountering a strange error when we use `delete_versions` on an empty `Dataset` and run `h5repack`. Here's the smallest reproducer I could come up with:
```
import shutil
import tempfile

import h5py
import numpy as np
import subprocess
from   versioned_hdf5           import VersionedHDF5File, delete_versions

if __name__ == '__main__':
    d = tempfile.mkdtemp()
    fn = d + '/data.h5'
    try:
        with h5py.File(fn, 'w') as f:
            vf = VersionedHDF5File(f)
            with vf.stage_version('r0') as sv:
                sv.create_dataset('key0', data=np.array([]), maxshape=(None,),
                                  chunks=(10000,), compression='lzf')

        with h5py.File(fn, 'r+') as f:
            vf = VersionedHDF5File(f)
            with vf.stage_version('r1') as sv:
                sv['key0'].resize((0,))

        tfn = tempfile.mktemp(dir=d)
        shutil.copy(fn, tfn)
        with h5py.File(tfn, 'r+') as f:
            delete_versions(f, ['r0'])
        p = subprocess.Popen(['h5repack', tfn, fn])
        p.wait()

        with h5py.File(fn, 'r+') as f:
            vf = VersionedHDF5File(f)
            with vf.stage_version('r2') as sv:
                sv['key0'].resize((0,))

        with h5py.File(fn, 'r') as f:
            vf = VersionedHDF5File(f)
            cv = vf[vf.current_version]
            print(cv['key0'][:])
    finally:
        shutil.rmtree(d)
```
This gives the following error
```
Traceback (most recent call last):
  File "/u/bessen/opensource/versioned-hdf5/delete_versions_h5repack_bug_5.py", line 49, in <module>
    print(cv['key0'][:])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/codemill/bessen/versioned_hdf5_env/lib64/python3.10/site-packages/h5py/_hl/dataset.py", line 768, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_selector.pyx", line 376, in h5py._selector.Reader.read
OSError: Can't read data (src and dest dataspaces have different number of elements selected)

Process finished with exit code 1
```
I think this error is from [this line](https://github.com/HDFGroup/hdf5/blob/bfef9945a88d52ad449b2f871c6d0a80ab94170f/src/H5Dio.c#L157) in `libhdf5`, but I don't eally understand what's going wrong here.

**Comment by asmeurer** [comment] 2023-02-21 00:29
I can reproduce this (unlike https://github.com/deshaw/versioned-hdf5/issues/238). I don't know what is going on. This issue and that one are similar, so it's possible they are related.

**Comment by asmeurer** [comment] 2023-02-21 05:25
Debugging this could potentially take over 10 hours, given that it may involve the C internals of HDF5 and/or h5repack. Without more investigation it's hard to say how long it will be. If you're okay with it I can spend up to 10 hours debugging this, and if we realize at any point that it will take longer than that to fix, we'll report back and make another estimate. What do you think?

**Comment by quarl** [comment] 2023-03-02 22:48
Thanks.  Please proceed with working on this.
This issue seems high priority & high severity.  The specific thing that led to finding this is a blocker on making progress on strategic goals.  And (for now, with uncertainty about the scope of the problem) we're worried that other cases also have data corruption even if it's not always surfacing immediately.

**Comment by peytondmurray** [comment] 2023-05-22 23:14
Quick update: while debugging this today, I found a separate issue that blocks the user from fetching data from a dataset - so I'm going to take care of that one first, since examining datasets will be important for solving this one.

**Comment by peytondmurray** [comment] 2023-05-25 23:49
After a little investigation, I was able to reproduce this _without_ `h5repack`:

```python
import pathlib
import shutil
import textwrap

import h5py
import numpy as np
from versioned_hdf5 import VersionedHDF5File, delete_versions

def print_info(fname):
    # Examine the most recent version
    with h5py.File(fname, "r") as f:
        vf = VersionedHDF5File(f)
        cv = vf[vf.current_version]
        items = "\n".join([
            f"f={f}",
            f"vf={vf}",
            f"cv={cv}",
            f"cv['key0'][:]={cv['key0'][:]}",
        ])
        text = textwrap.indent(items, "  ")
        print(fname + '\n' +  text)


# Clean out old data files
for p in pathlib.Path().glob("data*.h5"):
    p.unlink()

# Create new versioned file
with h5py.File('data1.h5', "w") as f:
    with VersionedHDF5File(f).stage_version("r0") as sv:
        sv.create_dataset(
            "key0",
            data=np.array([]),
            maxshape=(None,),
            chunks=(10000,),
            compression="lzf",
        )
print_info('data1.h5')

# Resize the dataset
shutil.copy('data1.h5', 'data2.h5')
with h5py.File('data2.h5', "r+") as f:
    with VersionedHDF5File(f).stage_version("r1") as sv:
        sv["key0"].resize((0,))
print_info('data2.h5')

# Delete version r0
shutil.copy('data2.h5', 'data3.h5')
with h5py.File('data3.h5', "r+") as f:
    delete_versions(f, ["r0"])
print_info('data3.h5')

# Resize the data again
shutil.copy('data3.h5', 'data4.h5')
with h5py.File('data4.h5', "r+") as f:
    with VersionedHDF5File(f).stage_version("r2") as sv:
        sv["key0"].resize((0,))
print_info('data4.h5')
```

Running this gives

```
data1.h5
  f=<HDF5 file "data1.h5" (mode r)>
  vf=<VersionedHDF5File object "data1.h5" (mode r)>
  cv=<HDF5 group "/_version_data/versions/r0" (1 members)>
  cv['key0'][:]=[]
data2.h5
  f=<HDF5 file "data2.h5" (mode r)>
  vf=<VersionedHDF5File object "data2.h5" (mode r)>
  cv=<HDF5 group "/_version_data/versions/r1" (1 members)>
  cv['key0'][:]=[]
data3.h5
  f=<HDF5 file "data3.h5" (mode r)>
  vf=<VersionedHDF5File object "data3.h5" (mode r)>
  cv=<HDF5 group "/_version_data/versions/r1" (1 members)>
  cv['key0'][:]=[]
Traceback (most recent call last):
  File "/home/pdmurray/Desktop/workspace/sandbox/vhdf/repro.py", line 60, in <module>
    print_info('data4.h5')
  File "/home/pdmurray/Desktop/workspace/sandbox/vhdf/repro.py", line 19, in print_info
    f"cv['key0'][:]={cv['key0'][:]}",
                     ~~~~~~~~~~^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/pdmurray/.pyenv/versions/vhdf/lib/python3.11/site-packages/h5py/_hl/dataset.py", line 745, in __getitem__
    return self._fast_reader.read(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_selector.pyx", line 376, in h5py._selector.Reader.read
OSError: Can't synchronously read data (src and dest dataspaces have different number of elements selected)
```

I'll continue looking into this later.

**Comment by ArvidJB** [comment] 2023-05-26 21:12
Great, eliminating `h5repack` makes this much simpler!

Note: we run `h5repack` because otherwise the file would not shrink after deleting versions.

**Comment by peytondmurray** [comment] 2023-05-29 21:00
Still not exactly sure what is going on, but it does look like something is interfering with the data. Between `data3.h5` and `data4.h5` `h5dump` becomes unable to print the data for the latest version:

![image](https://github.com/deshaw/versioned-hdf5/assets/14017872/4d3bfaae-0996-48db-a67e-0fc66894842d)

**Comment by peytondmurray** [comment] 2023-05-29 21:07
Here's the relevant section of `h5dump -pH <file>` comparing data3.h5 and data4.h5:
![image](https://github.com/deshaw/versioned-hdf5/assets/14017872/19ef3af1-358e-4388-98c2-08108048d675)

**Comment by peytondmurray** [comment] 2023-05-29 23:27
Another thing: `delete_versions` modifies the `/_version_info/key0/raw_data`:

```
data1 raw_data=[0. 0. 0. ... 0. 0. 0.]
data2 raw_data=[0. 0. 0. ... 0. 0. 0.]
data3 raw_data=[]
data4 raw_data=[]
```

`data1` and `data2` have 10000 values, each of which are 0. I think this is the default fill value for this kind of data.

**Comment by peytondmurray** [comment] 2023-05-30 19:55
@ArvidJB I've spent ~10 hours on this so far, and I need a little more time to finish debugging this rather difficult issue. I'm almost certain that this arises purely on the python side of things. The modifications to the raw data that are seen above is unexpected, and happens inside a function call that is meant to identify which data chunks are to be kept after a delete operation is run; I believe the affected code is here: https://github.com/deshaw/versioned-hdf5/blob/21b2b6c71a1ec7f98afcff41f119169b18aeca08/versioned_hdf5/replay.py#L135.

I'm going to talk to @asmeurer about this to get some insight about how we should expect this to behave, and I expect to have this resolved within 10 hours. Does that sound okay?

**Comment by ArvidJB** [comment] 2023-05-31 00:11
Yes, please go ahead.

**Comment by peytondmurray** [comment] 2023-06-05 20:06
Not sure why merging #248 didn't automatically close this, so I'm doing that now.

**Closed by peytondmurray** 2023-06-05 20:06 UTC
Labels: bug, help wanted
