### ISSUE TITLE
Creating multi-dimensional dataset with chunks and maxshape specified fails

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#64] opened 2020-05-22 15:05 UTC
This code
```
import h5py
import numpy as np
from versioned_hdf5 import VersionedHDF5File

with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        sv.create_dataset('bar', data=np.array([[1, 2], [2, 3]]),
                          maxshape=(None, None), chunks=(1000, 1000))
```
fails with
```
Traceback (most recent call last):
  File "/u/bessen/opensource/versioned-hdf5/create_dataset_maxshape.py", line 9, in <module>
    maxshape=(None, None), chunks=(1000, 1000))
  File "/opt/python/python-3.7/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/api.py", line 149, in stage_version
    compression_opts=group.compression_opts)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/versions.py", line 87, in commit_version
    compression_opts=compression_opts[name])
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/backend.py", line 60, in write_dataset
    compression=compression, compression_opts=compression_opts)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/backend.py", line 52, in create_base_dataset
    compression_opts=compression_opts)
  File "/usr/local/python/python-3.7/std/lib64/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/local/python/python-3.7/std/lib64/python3.7/site-packages/h5py/_hl/dataset.py", line 104, in make_new_dset
    raise ValueError(errmsg)
ValueError: Chunk shape must not be greater than data shape in any dimension. (1000, 1000) is not compatible with (0, 2)
```

**Comment by melissawm** [comment] 2020-07-27 22:51
I believe this has been fixed, as I'm not able to reproduce this error anymore. @ArvidJB can you confirm that we can close this?

**Comment by asmeurer** [comment] 2020-07-27 22:54
Note that `maxshape` currently does nothing. If you try to specify a maxshape that has anything other than None, you will get a warning. If you have a need for it, let me know. But be aware that it would just be a matter of doing type checking to prevent accidental resizes. The underlying raw dataset has to be resizable, and is only actually resized in the first dimension, so we would not use the actual maxshape in the underlying hdf5.

**Closed** 2020-07-29 18:23 UTC
Labels: high_priority

**Comment by ArvidJB** [comment] 2020-07-29 19:08
Thanks. I don't think we use a `maxshape` which is not a tuple of `None`s anywhere.
