### ISSUE TITLE
delete_versions high memory usage (PyInf#11623)

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#298] opened 2023-12-12 22:32 UTC
We observed that a number of our processes were running out of memory while running `delete_versions`. It turned out that we ended up choosing specific chunk sizes which inadvertently created a lot more chunks than ideal. Nonetheless it should be possible to reduce the memory consumed!

Here's some code to reproduce this. It creates a file with 100 versions, each version ended up having 35889 chunks:
```
import contextlib
import logging
import os
import resource
import shutil
import tempfile

import h5py
import numpy as np
import psutil

from   versioned_hdf5           import VersionedHDF5File, delete_versions


@contextlib.contextmanager
def memory_limit_ctx(buffer):
    # We want to set the soft limit to be the current usage + buffer.
    assert buffer > 0
    # get current memory usage
    used = psutil.Process(os.getpid()).memory_info().rss
    old_limit = resource.getrlimit(resource.RLIMIT_AS)
    new_limit = (used + buffer, old_limit[1])
    try:
        resource.setrlimit(resource.RLIMIT_AS, new_limit)
        yield
    finally:
        resource.setrlimit(resource.RLIMIT_AS, old_limit)


if __name__ == '__main__':
    # use an existing file with 100 versions
    filename = 'delete_versions_memory_usage.h5'

    # # to create the file uncomment on first run
    # logging.getLogger().setLevel(logging.INFO)
    # with h5py.File(filename, 'w') as f:
    #     vf = VersionedHDF5File(f)
    #     logging.info(f'creating version r{0}')
    #     with vf.stage_version(f'r0') as sv:
    #         sv.create_dataset('bitmap', data=np.zeros((35889, 5), dtype=np.uint8), compression='lzf',
    #                           dtype=np.dtype(np.uint8), maxshape=(None, None), chunks=(1, 10000))
    # with h5py.File(filename, 'r+') as f:
    #     vf = VersionedHDF5File(f)
    #     for i in range(1, 100):
    #         logging.info(f'creating version r{i}')
    #         with vf.stage_version(f'r{i}') as sv:
    #             sv['bitmap'][:] = np.random.randint(0, 256, 35889 * 5, dtype='uint8').reshape((35889, 5))

    # now delete some versions in place
    tmp_name = tempfile.mktemp('.h5')
    shutil.copy2(filename, tmp_name)
    try:
        # want to keep only every other version
        versions_to_delete = []
        with h5py.File(tmp_name, 'r') as f:
            vf = VersionedHDF5File(f)
            versions = reversed(sorted([(v, vf._versions[v].attrs['timestamp']) for v in vf._versions], key=lambda t: t[1]))
            for i, v in enumerate(versions):
                if i % 2 != 0:
                    versions_to_delete.append(v[0])

        # we should be able to run delete_versions with only 5 GB of additional memory
        with memory_limit_ctx(5 * (1 << 30)):
            # delete the versions
            with h5py.File(tmp_name, 'r+') as f:
                delete_versions(f, versions_to_delete)
    finally:
        os.remove(tmp_name)
```

From what I can tell the memory is consumed in two lines:
1. In `_recreate_raw_data` we open all version datasets via `dataset = f['_version_data/versions'][version_name][name]`. This seems to not release the memory allocated?
2. In `_recreate_virtual_dataset` we create the new virtual dataset in `tmp_dataset = group.create_virtual_dataset(tmp_path, layout, fillvalue=fillvalue)`. Is there a way to occasionally flush changes back to the file and clear up memory?

**Comment by peytondmurray** [comment] 2024-01-01 21:00
> From what I can tell the memory is consumed in two lines:
>
> 1. In _recreate_raw_data we open all version datasets via dataset = f['_version_data/versions'][version_name][name]. This seems to not release the memory allocated?

So I ran into some weird behavior here. I noticed that [this loop](https://github.com/deshaw/versioned-hdf5/blob/5c3b6d54dc49578883009d35fd33136bb09159f3/versioned_hdf5/replay.py#L205) allocates a dictionary of `{version_name: {virtual_slice: raw_data_slice}}`, but in the line that follows we take the union of the set of all chunks to keep:

```python
chunks_to_keep = set().union(
    *[map.values() for map in chunks_map.values()]
)
```
The `MemoryError` I saw was here - which kind of makes sense: we're constructing a potentially large list of large lists here. I'll spend a few hours here to do a few optimizations that should allow us to avoid allocating all these dicts and lists. I'll report back once I'm done.

> 2. In _recreate_virtual_dataset we create the new virtual dataset in tmp_dataset = group.create_virtual_dataset(tmp_path, layout, fillvalue=fillvalue). Is there a way to occasionally flush changes back to the file and clear up memory?

Probably we can call `gc.collect()` here. I'll try the first optimizations and then look deeper into this.

**Comment by peytondmurray** [comment] 2024-01-08 20:59
I was able to get a ~33% speedup of the part of the code that figures out what chunks to keep over the previous implementation, and the reproducer is no longer bottlenecked at that part of the code. However, we still don't have enough memory to finish running `delete_versions`. The failure happens during the recreation of the hashtable, with peak memory usage topping out at 6.4 GiB.

![newplot](https://github.com/deshaw/versioned-hdf5/assets/14017872/e88040bc-3954-450d-b540-199b630045c1)

The memory usage comes from

1. Keeping a dictionary mapping old chunks of the raw dataset to their new locations in the recreated raw dataset
2. Recreating the hashtable, which requires the inverse of the old hashtable to be kept in memory at the same time as we are building a new hashtable

Here's the flamegraph:

![image](https://github.com/deshaw/versioned-hdf5/assets/14017872/01fff390-056f-4ced-8e3e-8995f675bc99)

I'll make a PR with the refactor that I currently have since we gain a substantial speedup (30s on my local machine) over what we had before.

**Comment by peytondmurray** [comment] 2024-01-29 01:58
Given that this issue is pretty well understood at this point and that there's already been some improvements in memory consumption in https://github.com/deshaw/versioned-hdf5/pull/300, I'm closing this issue for now. If we need to optimize memory usage further, we're going to have to start looking more deeply for ways to save memory.

**Closed by peytondmurray** 2024-01-29 01:58 UTC
