### ISSUE TITLE
Bug when creating empty dataset - PyInf#12125

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#314] opened 2024-03-05 00:43 UTC
We ran into a weird bug related to some ancient code in `create_virtual_dataset` where we create a virtual dataset of shape `(1,)` if the "raw_data" is empty:
https://github.com/deshaw/versioned-hdf5/blob/d6c709c36c039c6252ec7ed51fe411b32f8aa145/versioned_hdf5/backend.py#L400-L404
Normally this never happens since we would normally not get here if the dataset is empty. To reproduce this we need to create a non-empty dataset which later turns empty and then use `delete_versions` to delete all non-empty versions. A subsequent upsert then creates a corrupted empty virtual dataset:
```
import h5py
import numpy as np
from   versioned_hdf5           import VersionedHDF5File
from   versioned_hdf5.replay    import delete_versions

if __name__ == '__main__':
    path = '/var/tmp/12125.h5'
    with h5py.File(path, 'w') as f:
        vf = VersionedHDF5File(f)
        with vf.stage_version('r0') as sv:
            sv.create_dataset('values', data=np.array([1, 2, 3]))

    with h5py.File(path, 'r+') as f:
        vf = VersionedHDF5File(f)
        with vf.stage_version('r1') as sv:
            sv['values'].resize((0,))

    with h5py.File(path, 'r+') as f:
        delete_versions(f, ['r0'])

    with h5py.File(path, 'r+') as f:
        vf = VersionedHDF5File(f)
        with vf.stage_version('r2') as sv:
            sv['values'].resize((0,))

    with h5py.File(path, 'r+') as f:
        vf = VersionedHDF5File(f)
        cv = vf[vf.current_version]
        print(cv['values'][:])
```
gives the following error
```
Traceback (most recent call last):
  File "/codemill/bessen/opensource/versioned-hdf5/12125_empty_dataset_reproducer.py", line 29, in <module>
    print(cv['values'][:])
          ~~~~~~~~~~~~^^^
  File "/usr/local/python/python3/std/lib64/python3.11/site-packages/versioned_hdf5/wrappers.py", line 1129, in __getitem__
    return self.dataset.__getitem__(index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/python/python3/std/lib64/python3.11/site-packages/versioned_hdf5/wrappers.py", line 658, in __getitem__
    return super().__getitem__(idx.raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/python/python3/std/lib64/python3.11/site-packages/h5py/_hl/dataset.py", line 768, in __getitem__
    return self._fast_reader.read(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_selector.pyx", line 376, in h5py._selector.Reader.read
OSError: Can't synchronously read data (src and dest dataspaces have different number of elements selected)
```

**Comment by peytondmurray** [comment] 2024-03-11 20:34
@ArvidJB Thanks for the information and the clean reproducer, this definitely seems like undefined behavior that should be eliminated. 

I'm trying to understand the intended user journey here. According to the [`h5py` docs](https://docs.h5py.org/en/stable/high/dataset.html#resizable-datasets), `ds.resize` should discard data if the new size is smaller than the current size. So the way I read your reproducer is

1. Create a dataset of size 3
2. Create a new version and resize the dataset, discarding the (virtual) data
3. Delete the first version; `raw_data` should now have nothing in it. At this point using your reproducer I can see that the raw data is empty and has size 0:

```
(Pdb++) f['_version_data']['values']['raw_data'][:]
array([], dtype=int64)
```

4. Create a new version, resizing the `values` virtual dataset from `r1` to size `(0,)`. What purpose does this step serve, I wonder? What are you trying to achieve here? If I remove this step the code executes successfully.
5. Print the content of `r2`

In addition to the questions in step 4, what is the user trying to do in this sequence of operations? Also, is there significance to using multiple context managers for opening/closing the file between versions (are you trying to flush output with this, etc)? I found that if I remove the various context managers there's no error:

```python
import h5py
import numpy as np
from versioned_hdf5 import VersionedHDF5File
from versioned_hdf5.replay import delete_versions

if __name__ == "__main__":
    path = "/var/tmp/12125.h5"
    with h5py.File(path, "w") as f:
        vf = VersionedHDF5File(f)
        with vf.stage_version("r0") as sv:
            sv.create_dataset("values", data=np.array([1, 2, 3]))

        with vf.stage_version("r1") as sv:
            sv["values"].resize((0,))

        delete_versions(f, ["r0"])

        with vf.stage_version("r2") as sv:
            sv["values"].resize((0,))

        cv = vf[vf.current_version]
        print(cv["values"][:])
```

I feel like there are two components to this issue for me:

1. Fix whatever bug is causing the issue reported so that the user can't break a dataset. It doesn't make sense to me to allocate a virtual dataset of shape `(1,)` if the raw data is empty. I seem to remember a discussion about it being impossible to create empty virtual datasets with h5py, but I can't recall what the context was for that conversation or whether it is even relevant with newer versions of h5py.
2. Understand the user journey

**Closed** 2024-03-25 20:23 UTC
