### ISSUE TITLE
Writing empty dataset fails

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#98] opened 2020-07-15 22:58 UTC
```
import h5py
import numpy as np
from versioned_hdf5 import VersionedHDF5File

with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        sv['bar'] = np.arange(0)
```
fails with
```
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/backend.py", line 152, in create_virtual_dataset
    shape = (chunk_size*(len(slices) - 1) + slices[-1].stop - slices[-1].start,) + chunks[1:]
IndexError: list index out of range
```
in master and with
```
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/backend.py", line 155, in create_virtual_dataset
    shape = tuple([max(c.args[i].stop for c in slices) for i in range(len(chunks))])
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/backend.py", line 155, in <listcomp>
    shape = tuple([max(c.args[i].stop for c in slices) for i in range(len(chunks))])
ValueError: max() arg is an empty sequence
```
in asmeurer/as_subindex.

**Comment by scopatz** [comment] 2020-07-22 18:20
Closed as duplicate of #24

**Comment by ArvidJB** [comment] 2020-08-06 12:50
This is still not working, can you take a look? I don't think it had anything to do with #24.

**Comment by ArvidJB** [comment] 2020-09-03 18:58
Can you take another look at this? I think this is blocking us now.

**Comment by asmeurer** [comment] 2020-09-07 21:18
The OP example works for me in master. Are there any other issues with this?

**Comment by ArvidJB** [comment] 2020-09-09 13:26
You are right, the original code works now. But I still get the same kind of errors with the following code:
```
with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        sv['bar'] = np.arange(10)

with h5py.File('foo.h5', 'r+') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('1') as sv:
        sv['bar'].resize((0,))

with h5py.File('foo.h5', 'r') as f:
    vf = VersionedHDF5File(f)
    cv = vf[vf.current_version]
    print(cv['bar'][:])
```
the errors are
```
Traceback (most recent call last):
  File "/u/bessen/opensource/versioned-hdf5/write_empty_dataset.py", line 13, in <module>
    sv['bar'].resize((0,))
  File "/opt/python/python-3.7/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/api.py", line 171, in stage_version
    timestamp=timestamp)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/versions.py", line 97, in commit_version
    slices = write_dataset_chunks(f, name, data)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/backend.py", line 127, in write_dataset_chunks
    range(len(chunks)))
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/backend.py", line 126, in <genexpr>
    shape = tuple(max(c.args[i].stop for c in data_dict) for i in
ValueError: max() arg is an empty sequence
```

**Comment by ArvidJB** [comment] 2020-09-09 13:28
This is with up-to-date master and with ndindex from https://github.com/asmeurer/ndindex/tree/integerarray-as_subindex

**Comment by asmeurer** [comment] 2020-09-09 18:05
I see. I guess `resize` isn't working properly.

**Closed** 2020-09-09 23:54 UTC
Labels: high_priority

**Comment by ArvidJB** [comment] 2020-09-10 09:28
Thanks, this works now with #130 .
